### ISSUE TITLE
"cargo install register-evm-agent" error

### ISSUE THREAD

**Issue by wureny** [bitfinity-network/bitfinity-evm-sdk#85]
When i use the command `cargo install register-evm-agent`,
 i get the error: "could not find `register-evm-agent` in registry `crates-io` with version `*`"
What causes this?
how to solve it?
<img width="559" alt="CleanShot 2023-12-17 at 22 00 11@2x" src="https://github.com/bitfinity-network/bitfinity-evm-sdk/assets/112567966/8c961fea-84fd-42eb-9ad4-3855856b6a5a">

**Comment by ufoscout** [comment]
Hi @wureny 
you can download the  `register-evm-agent`  binaries from the [Github releases page](https://github.com/bitfinity-network/bitfinity-evm-sdk/releases)
